# Generated by Django 3.1.6 on 2021-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='mobile',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
